#!/usr/bin/env bash

yay -S --noconfirm --needed \
    brightnessctl \
    blueman \
    bluez \
    bluez-utils \
    grim \
    cliphist \
    ttf-font-awesome \
    thunar \
    man-db \
    jq \
    adwaita-dark \
    pavucontrol \
    grim \
    slurp \
    imv \
    spotify \
    hyprshot \
